Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============
before puzzle
[1, 2, 3, 4] [] []
after puzzle
[] [] [1, 2, 3, 4]

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============
2023-02-03

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============
2023-02-03
2023-02-04
2023-02-05
2023-02-06
2023-02-07
2023-02-08
2023-02-09
2023-02-10
2023-02-11
2023-02-12

================ RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ===============
2023-02-03
2023-05-04
2023-05-05
2023-05-06
2023-05-07
2023-05-08
2023-05-09
2023-05-10
2023-05-11
2023-05-12
2023-05-13
2023-05-14
2023-05-15
2023-05-16
2023-05-17
2023-05-18
2023-05-19
2023-05-20
2023-05-21
2023-05-22
2023-05-23
2023-05-24
2023-05-25
2023-05-26
2023-05-27
2023-05-28
2023-05-29
2023-05-30
2023-05-31
2023-06-01

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
2023-02-03
2023-05-14
2023-05-15
2023-05-16
2023-05-17
2023-05-18
2023-05-19
2023-05-20
2023-05-21
2023-05-22
2023-05-23
2023-05-24
2023-05-25
2023-05-26
2023-05-27
2023-05-28
2023-05-29
2023-05-30
2023-05-31
2023-06-01
2023-06-02
2023-06-03
2023-06-04
2023-06-05
2023-06-06
2023-06-07
2023-06-08
2023-06-09
2023-06-10
2023-06-11

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 31, in <module>
    while(n!=0):
NameError: name 'n' is not defined

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 31, in <module>
    while(n!=0):
NameError: name 'n' is not defined

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 29, in <module>
    while(n!=0):
NameError: name 'n' is not defined

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 32, in <module>
    s=s+fact()
NameError: name 's' is not defined

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 32, in <module>
    sum=sum+fact()
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'NoneType'

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 32, in <module>
    sum=sum+fact()
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'NoneType'

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 32, in <module>
    sum1=sum1+fact()
NameError: name 'sum1' is not defined. Did you mean: 'sum'?

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 33, in <module>
    sum1=sum1+fact()
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 33, in <module>
    sum1=sum1+f
NameError: name 'f' is not defined
>>> 
================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 33, in <module>
    sum1=sum1+fact(r)
TypeError: fact() takes 0 positional arguments but 1 was given

... 
>>> 
================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 33, in <module>
    sum1=sum1+fact(r)
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
>>> 
================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
enter a number:145
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 33, in <module>
    sum1=sum1+int(fact(r))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
>>> 
================================= RESTART: C:/Users/91938/Desktop/day_5/day5_2.py ================================
Traceback (most recent call last):
  File "C:/Users/91938/Desktop/day_5/day5_2.py", line 31, in <module>
    sum,temp=0
TypeError: cannot unpack non-iterable int object
